---
- hosts: localhost
  connection: local
  become: true

  vars:
    dotfiles_repo: "git@github.com:thomasgroch/dotfiles.git"
    dotfiles_bare_dir: "~/.dotfiles-bare"
    ssh_key_path: "~/.ssh/id_ed25519"

  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/users.yml
    - include: tasks/packages.yml
    - include: tasks/gnome.yml
    - include: tasks/dotfiles.yml
    - include: tasks/cron.yml