---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/users.yml
    - include: tasks/packages.yml
    - include: tasks/gnome.yml
    - include: tasks/dotfiles.yml
    - include: tasks/cron.yml
