---
- name: Verificar se as variáveis necessárias estão definidas
  assert:
    that:
      - dotfiles_bare_dir is defined
      - dotfiles_home_dir is defined
      - dotfiles_repo is defined
    fail_msg: "Variáveis necessárias não estão definidas"
  tags:
    - always

- name: Verificar se oh-my-zsh está instalado
  stat:
    path: "{{ dotfiles_home_dir }}/.oh-my-zsh"
  become_user: "tg"
  register: omz_stat

- name: Instalar oh-my-zsh
  shell: |
    curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
  args:
    creates: "{{ dotfiles_home_dir }}/.oh-my-zsh"
  become_user: "tg"
  when: not omz_stat.stat.exists
  environment:
    RUNZSH: "no"
    KEEP_ZSHRC: "yes"
  tags:
    - dotfiles
    - zsh

- name: Verificar se os diretórios do Oh My Zsh existem
  stat:
    path: "{{ item }}"
  register: omz_dir_stat
  become_user: "tg"
  loop:
    - "{{ dotfiles_home_dir }}/.oh-my-zsh/cache/completions"
    - "{{ dotfiles_home_dir }}/.oh-my-zsh-custom"

- name: Corrigir permissões dos diretórios do Oh My Zsh
  file:
    path: "{{ item.item }}"
    mode: '0755'
    recurse: yes
  loop: "{{ omz_dir_stat.results }}"
  when: item.stat.exists
  become: yes
  become_user: tg
  tags:
    - dotfiles
    - fix_permissions

- name: Verificar se o repositório dotfiles já existe
  stat:
    path: "{{ dotfiles_bare_dir }}"
  register: dotfiles_repo_stat

- name: Criar link simbólico para .git
  file:
    src: "{{ dotfiles_bare_dir }}"
    dest: "{{ dotfiles_home_dir }}/.git"
    state: link
    force: yes
    follow: no
  become_user: tg

- name: Verificar se existem mudanças não comitadas
  command: git --git-dir={{ dotfiles_bare_dir }} --work-tree={{ dotfiles_home_dir }} status --porcelain
  become_user: "tg"
  register: git_status
  changed_when: false
  failed_when: false
  when: dotfiles_repo_stat.stat.exists

- name: Ensure Ansible temporary directory exists
  file:
    path: /tmp/.ansible/tmp
    state: directory
    mode: '0777'
    recurse: yes
  become: yes

- name: Clonar ou atualizar repositório bare para dotfiles
  git:
    repo: "{{ dotfiles_repo }}"
    version: main
    bare: yes
    dest: "{{ dotfiles_bare_dir }}"
    accept_hostkey: yes
    key_file: "{{ ansible_ssh_private_key_file }}"
    update: yes
    track_submodules: yes
    recursive: yes
  register: git_clone
  become_user: "tg"
  tags: 
    - dotfiles
    - sync

- name: Atualizar submódulos Git
  command: git --git-dir={{ dotfiles_bare_dir }} --work-tree={{ dotfiles_home_dir }} submodule update --init --recursive
  become_user: "tg"
  when: git_clone.changed
  tags:
    - dotfiles
    - sync

- name: Fazer stash se houver mudanças não comitadas
  command: git --git-dir={{ dotfiles_bare_dir }} --work-tree={{ dotfiles_home_dir }} stash
  become_user: "tg"
  when: 
    - git_status is succeeded
    - git_status.stdout is defined
    - git_status.stdout | length > 0
  tags:
    - dotfiles
    - backup

- name: Sobrescrever dotfiles padrão do sistema no primeiro uso
  command: git --git-dir={{ dotfiles_bare_dir }} --work-tree={{ dotfiles_home_dir }} reset --hard
  become_user: "tg"
  when: 
    - git_clone.changed 
    - not dotfiles_repo_stat.stat.exists
  tags:
    - dotfiles
    - sync

# Adiciona o segundo usuário ao grupo do usuário principal (se necessário)
# - name: Adicionar usuário secundário ao grupo do usuário principal
#   user:
#     name: ansible
#     group: tg
#     append: yes

# - name: Conceder permissão de leitura para o grupo na pasta do usuário principal
#   file:
#     path: "{{ dotfiles_bare_dir }}"
#     owner: tg
#     group: tg
#     mode: '0750'
#     recurse: yes

# - name: Garantir permissões de leitura para ansible no repositório de dotfiles
#   acl:
#     path: "{{ dotfiles_bare_dir }}"
#     entity: ansible
#     etype: user
#     permissions: rx
#     state: present
#     recursive: yes

# - name: Garantir que o diretório de dotfiles é considerado seguro pelo Git para o usuário ansible
#   command: git config --global --add safe.directory /home/tg/.dotfiles-bare
#   become_user: ansible
#   ignore_errors: yes  # Ignorar erros se o diretório já estiver configurado

# - name: Garantir permissões corretas para o repositório bare
#   file:
#     path: "{{ dotfiles_bare_dir }}"
#     owner: tg
#     group: ansible
#     mode: '0755'
#     recurse: yes
#   # when: git_clone.changed

# - name: Debug dotfiles_repo_stat
#   debug:
#     var: dotfiles_repo_stat


# - name: Debug git status
#   debug:
#     var: git_status

# - name: Verificar se existe saída no git_status
#   debug:
#     msg: "stdout está presente: {{ 'stdout' in git_status }}"

- name: Configurar Git para não mostrar arquivos não rastreados
  git_config:
    name: status.showUntrackedFiles
    scope: local
    repo: "{{ dotfiles_bare_dir }}"
    value: 'no'
  become_user: tg

- name: Habilitar sparse checkout no Git
  git_config:
    name: core.sparseCheckout
    scope: local
    repo: "{{ dotfiles_bare_dir }}"
    value: 'true'
  become_user: tg

# - name: Executar script de provisionamento se houver mudanças
#   command: /usr/local/bin/provision.sh
#   when: git_clone.changed
#   ignore_errors: yes

# sudo chsh tg -s /bin/zsh
