---
- name: Adicionar repositório ao apt
  apt_repository:
    repo: ppa:linuxuprising/guake
    state: present

- name: Aguardar até que o bloqueio do APT seja liberado
  shell: while fuser /var/lib/dpkg/lock >/dev/null 2>&1 || fuser /var/lib/apt/lists/lock >/dev/null 2>&1; do sleep 1; done

- name: Instalar pacotes
  vars:
    packages: "{{ lookup('file', 'packages.txt').splitlines() | select('match', '^[^#]') | list }}"
  package:
    name: "{{ item }}"
    update_cache: yes
  with_items: "{{ packages }}"
  when: item != ""
  register: apt_result
  retries: 5
  delay: 10
  until: apt_result is succeeded

- name: Adicionar repositório Flathub
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  args:
    creates: /var/lib/flatpak/repo/flathub

- name: Instalar Moonlight via Flatpak
  flatpak:
    name: com.moonlight_stream.Moonlight
    state: present
    remote: flathub

- name: Obter a versão mais recente do lazygit
  shell: |
    curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*'
  register: lazygit_version

- name: Baixar tarball do lazygit
  shell: |
    curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_{{ lazygit_version.stdout }}_Linux_x86_64.tar.gz"
  args:
    creates: lazygit.tar.gz

- name: Extrair lazygit
  shell: |
    tar xf lazygit.tar.gz lazygit
  args:
    creates: lazygit

- name: Instalar lazygit
  become: yes
  shell: |
    install lazygit /usr/local/bin
    
# - name: Check if Go is installed
#   command: go version
#   register: go_installed
#   ignore_errors: yes

# - name: Download Go archive
#   get_url:
#     url: https://storage.googleapis.com/golang/go1.4.linux-amd64.tar.gz
#     dest: /tmp/go.tar.gz
#   when: go_installed.rc != 0  # Proceed only if Go is not installed

# - name: Extract Go to /usr/local
#   unarchive:
#     src: /tmp/go.tar.gz
#     dest: /usr/local
#     remote_src: yes
#   when: go_installed.rc != 0  # Only extract if Go was just downloaded

# - name: Clean up Go archive
#   file:
#     path: /tmp/go.tar.gz
#     state: absent
#   when: go_installed.rc != 0  # Only clean up if Go was downloaded

# - name: Update font cache
#   command: fc-cache -fv


- name: Add ZeroTier repository
  ansible.builtin.apt_repository:
    repo: "deb http://download.zerotier.com/debian/buster buster main"
    state: present
    filename: zerotier
  when: ansible_os_family == 'Debian'

- name: Add ZeroTier GPG key
  ansible.builtin.apt_key:
    url: "https://download.zerotier.com/contact%40zerotier.com.gpg"
    state: present
  when: ansible_os_family == 'Debian'

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install ZeroTier on Debian-based systems
  ansible.builtin.apt:
    name: zerotier-one
    state: present
  when: ansible_os_family == 'Debian'

- name: Install ZeroTier on RHEL-based systems
  ansible.builtin.yum:
    name: zerotier-one
    state: present
  when: ansible_os_family == 'RedHat'

- name: Join ZeroTier network
  ansible.builtin.command:
    cmd: zerotier-cli join abfd31bd47bb29b7
    creates: /var/lib/zerotier-one/networks.d/abfd31bd47bb29b7.conf

- name: Enable and start the ZeroTier service
  ansible.builtin.systemd:
    name: zerotier-one
    enabled: yes
    state: started
