---
#- name: Adicionar repositório ao apt
#  apt_repository:
#    repo: ppa:
#    state: present

- name: Install apt packages
  package:
    name:
      - dconf-cli
      - python3-psutil
      - gnome-tweaks
      - neofetch
      - btop
      - icdiff
      - tar
      - wget
      - rustc
      - cargo
    update_cache: yes

- name: Check if Go is installed
  command: go version
  register: go_installed
  ignore_errors: yes

- name: Download Go archive
  get_url:
    url: https://storage.googleapis.com/golang/go1.4.linux-amd64.tar.gz
    dest: /tmp/go.tar.gz
  when: go_installed.rc != 0  # Proceed only if Go is not installed

- name: Extract Go to /usr/local
  unarchive:
    src: /tmp/go.tar.gz
    dest: /usr/local
    remote_src: yes
  when: go_installed.rc != 0  # Only extract if Go was just downloaded

- name: Add Go to PATH in .zshrc
  become: yes
  become_user: tg
  lineinfile:
    path: $HOME/.zshrc
    line: 'export PATH=$PATH:/usr/local/go/bin'
    state: present
  when: go_installed.rc != 0  # Only add to PATH if Go was just installed

- name: Clean up Go archive
  file:
    path: /tmp/go.tar.gz
    state: absent
  when: go_installed.rc != 0  # Only clean up if Go was downloaded

- name: Update font cache
  command: fc-cache -fv