### User management playbook

- name: Create required groups
  group:
    name: "{{ item }}"
    state: present
  loop:
    - ansible
    - tg
    - users
    - adm
    - sudo
    - lpadmin

- name: Create ansible user
  user:
    name: "ansible"
    uid: 900
    group: "ansible"
    groups: "ansible,tg,users,adm,sudo,lpadmin"
    state: present
    comment: "user"
    shell: /usr/bin/zsh
    password: "{{ user_password | password_hash('sha512') }}"

- name: Copy sudoers_ansible
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: Copy ssh agent config
  copy:
    src: files/ssh_agent
    dest: /etc/sudoers.d/ssh_agent
    owner: root
    group: root
    mode: 0440

- name: Create tg user
  user:
    name: "tg"
    group: "tg"
    groups: "tg,users,adm,sudo,lpadmin"
    state: present
    comment: "user"
    shell: /usr/bin/zsh
    password: "{{ user_password | password_hash('sha512') }}"
