### User management playbook

- name: create ansible user
  user:
    name: "ansible"
    uid: 900
    group: "ansible"
    groups: "ansible,tg,users,adm,sudo,lpadmin"
    state: present
    comment: "user"
    shell: /usr/bin/zsh

- name: copy sudoers_ansible
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: copy ssh agent config
  copy:
    src: files/ssh_agent
    dest: /etc/sudoers.d/ssh_agent
    owner: root
    group: root
    mode: 0440

- name: create tg user
  user:
    name: "tg"
    group: "tg"
    groups: "tg,users,adm,sudo,lpadmin"
    state: present
    comment: "user"
    shell: /usr/bin/zsh
