#!/bin/bash

LOCALUSER="tg"
ANSIBLEUSER="ansible"
BRANCH="main"
LOGFILE="/home/${ANSIBLEUSER}/ansible.log"
REPO="https://github.com/thomasgroch/ansible_popos"

# Função para verificar processos ansible-pull em execução
check_running() {
  if pgrep -f ansible-pull > /dev/null; then
    printf "\n$(date +"%Y-%m-%d %H:%M:%S") Um processo ansible-pull já está em execução.\nSaindo.\n" | tee -a "$LOGFILE"
    exit 1
  fi
}

# Lógica principal do script
check_running
COMMON_OPTS="--vault-password-file /home/${ANSIBLEUSER}/.vault_key --url $REPO --checkout $BRANCH"

# Executar ansible-pull
printf "\n$(date +"%Y-%m-%d %H:%M:%S") Executando ansible-pull...\n" | tee -a "$LOGFILE"
if [[ ! -z "$1" ]]; then
  ansible-ppull --tags "$1" $COMMON_OPTS >> "$LOGFILE" 2>&1
else
  ansible-pull $COMMON_OPTS >> "$LOGFILE" 2>&1
fi

if [ $? -eq 0 ]; then
  printf "\n$(date +"%Y-%m-%d %H:%M:%S") ansible-pull executado com sucesso.\n" | tee -a "$LOGFILE"
else
  printf "\n$(date +"%Y-%m-%d %H:%M:%S") Falha na execução do ansible-pull.\n" | tee -a "$LOGFILE"
fi
