name: Docker Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Build Docker image
      run: docker build -t ansible-popos-test .
      
    - name: Run Docker container
      run: |
        docker run --rm ansible-popos-test
